use std::collections::HashMap;

use num_bigint::BigInt;
use serde::{Deserialize, Serialize};

use crate::prover::MultiuseProver;

// Contains non-mangled symbols called from C
mod runtime;
#[cfg(test)]
mod tests;

pub type ComputeWitnessFn = fn(Vec<(String, Vec<BigInt>)>) -> Vec<BigInt>;

/// Summary of a linked w2c2 .a file.
#[derive(Debug)]
struct LinkedLib {
    curve: &'static str,
    circuit: &'static str,
    // rust_witness macro generated code is generic and allows any iterator returning owned
    // data, but we need to store it here, so it must be a specific type.
    compute_witness: ComputeWitnessFn,
}

/// Used for circuit selection.
#[derive(Debug, Hash, PartialEq, Eq, Serialize, Deserialize, Clone)]
pub struct CircuitId {
    pub curve: String,
    pub circuit: String,
    pub contributions: usize,
}
/// Data/Config needed for processing, not used for circuit selection.
#[derive(Debug)]
pub struct CircuitEntry {
    pub compute_witness: ComputeWitnessFn,
    pub prover: Option<MultiuseProver>,
    pub params: Option<CircuitParams>,
}

/// The data needed for knowing the input data layout.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct CircuitParams {
    pub header: usize,      // JWT header length: b64(header)
    pub payload: usize,     // JWT payload length: b64(header) + '.' + b64(body)
    pub sd_entries: usize,  // Max number of entries in "_sd"
    pub disclosures: usize, // Max number of disclosures
    pub sdbytes: usize,     // Bytes per disclosure
    pub path_depth: usize,  // Number of segments/parts in the key (currently unused)
}

// Generate list of linked curve+circuit w2c2 code + macro invocations (generated by build.rs)
// Example:
// ```
// rust_witness::witness!(bls12381minimal);
// fn bls12381minimal_shim(i: Vec<(String, Vec<BigInt>)>) -> Vec<BigInt> { bls12381minimal_witness(i) }
//
// const LINKED: &[LinkedLib] = &[
//     LinkedLib { curve: "bls12-381", circuit: "minimal", compute_witness: bls12381minimal_shim },
// ];
// ```
include!(concat!(env!("OUT_DIR"), "/witness_codegen.rs"));

/// Finds matching zkeys (at runtime) and create a lookup table.
pub fn get_circuits() -> HashMap<CircuitId, CircuitEntry> {
    let mut out = HashMap::new();
    // We can only process circuits that have been linked at compile time.
    // This is a bit inefficient, as it iterates the cruve directory for every circuit. But
    // this only happens once.
    for linked in LINKED {
        // Find usable zkeys.
        // let dir = format!("zkey/{}/{}.{}.zkey", linked.curve, linked.circuit)

        for e in std::fs::read_dir(format!("zkey/{}", linked.curve)).unwrap() {
            let e = e.unwrap();
            if !e.file_type().unwrap().is_file() {
                continue;
            }
            let name = e.file_name().into_string().unwrap();
            let Some((base, ext)) = name.rsplit_once('.') else {
                continue;
            };
            if ext != "zkey" {
                continue;
            }
            let Some((circuit, contributions)) = base.rsplit_once('.') else {
                eprintln!("Skipping zkey without contributions number: {name}");
                continue;
            };
            // PERFORMANCE: We are potentially wasting a bunch of work here.
            if circuit != linked.circuit {
                continue;
            }
            let Ok(contributions) = contributions.parse() else {
                continue;
            };

            let params = circuit_params(linked.circuit);
            out.insert(
                CircuitId {
                    curve: linked.curve.to_owned(),
                    circuit: linked.circuit.to_owned(),
                    contributions,
                },
                CircuitEntry {
                    compute_witness: linked.compute_witness,
                    prover: None,
                    params,
                },
            );
        }
    }

    out
}

impl CircuitId {
    pub fn zkey_path(&self) -> String {
        format!(
            "zkey/{}/{}.{:04}.zkey",
            self.curve, self.circuit, self.contributions
        )
    }
    pub fn cardano_path(&self) -> String {
        // TODO: This should also depend on the contributions. Update the makefile accordingly!
        format!("zkey/{}/{}.cardano.json", self.curve, self.circuit)
    }
}

// Lookup table (we are not parsing that from the circom file itself.
// If these do not match the circuit configuration witness generation will fail silently.
fn circuit_params(name: &str) -> Option<CircuitParams> {
    match name {
        "sdjwt_es256_sha256_1claim" => Some(CircuitParams {
            header: 2048,
            payload: 3072,
            sd_entries: 5,
            disclosures: 1,
            sdbytes: 256,
            path_depth: 1,
        }),
        "small" | "small_nocrypto" => Some(CircuitParams {
            header: 32,
            payload: 192,
            sd_entries: 1,
            disclosures: 1,
            sdbytes: 192,
            path_depth: 1,
        }),
        _ => None,
    }
}
