name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  rust-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - run: rustup update 1.90 && rustup default 1.90
      - run: cargo fmt --all --check

  rust-clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - run: rustup update 1.90 && rustup default 1.90
      - uses: Swatinem/rust-cache@v2
      - name: make init
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          make init
      - run: cargo clippy --all-targets --locked -- -D warnings

  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update 1.90 && rustup default 1.90
      - uses: taiki-e/install-action@nextest
      - run: cargo install --locked --git https://github.com/iden3/circom.git
      - run: npm install -g snarkjs
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.21
      - uses: Swatinem/rust-cache@v2
      - name: make init
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          make init
      # NOTE: We are using the minimal circuit, for which way smaller ptau sizes are possible.
      - name: Compile circuit and generate key material
        run: >
          make prep-tests-bn254-minimal
          PTAU_SIZE_BN254=05
          PTAU_SIZE_BLS12381=05
      # NOTE: We currently use this renaming trick, as the eudi2web3 (currently) has the circuit name hard coded.
      # Most likely we will change this and select the circuit dynamically (+ choice on which one to use).
      - name: Use minimal circuit for tests
        run: |
          mv zkey/bn254/minimal_js zkey/bn254/sdjwt_es256_sha256_1claim_js
          mv zkey/bn254/sdjwt_es256_sha256_1claim_js/minimal.wasm zkey/bn254/sdjwt_es256_sha256_1claim_js/sdjwt_es256_sha256_1claim.wasm
          mv zkey/bn254/minimal.r1cs zkey/bn254/sdjwt_es256_sha256_1claim.r1cs
          mv zkey/bn254/minimal.zkey zkey/bn254/sdjwt_es256_sha256_1claim.zkey
          mv zkey/bn254/minimal.cardano.json zkey/bn254/sdjwt_es256_sha256_1claim.cardano.json
      # Note: This does not run slow tests or tests communicating with a cardano testnet.
      - run: cargo nextest run --locked --no-fail-fast
      - run: cargo test --doc --locked

  cardano-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.21
      - run: aiken fmt --check
        working-directory: verifier/cardano
      - run: aiken check -D
        working-directory: verifier/cardano
      - run: aiken build
        working-directory: verifier/cardano

