name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  rust-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - run: rustup update 1.90 && rustup default 1.90
      - run: cargo fmt --all --check

  rust-clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - run: rustup update 1.90 && rustup default 1.90
      - uses: Swatinem/rust-cache@v2
      - name: make init
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          make init
      - run: cargo clippy --all-targets --locked -- -D warnings

  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update 1.90 && rustup default 1.90
      - uses: Swatinem/rust-cache@v2
      - name: Get w2c2 version
        id: w2c2
        run: |
          REV=$(git ls-remote https://github.com/vivianjeng/w2c2 HEAD | cut -f1)
          echo "rev=$REV" >> $GITHUB_OUTPUT
      - name: Cache w2c2
        uses: actions/cache@v4
        with:
          path: |
            target/w2c2
            target/w2c2_includes
          key: ${{ runner.os }}-w2c2-${{ hashFiles('scripts/install_w2c2.sh') }}-%{{ steps.w2c2.outputs.rev }}
      - uses: taiki-e/install-action@nextest
      # - run: cargo install --locked --git https://github.com/iden3/circom.git
      - name: Install circom binary
        run: |
          curl -L -o circom https://github.com/iden3/circom/releases/download/v2.2.3/circom-linux-amd64
          chmod +x circom
          sudo mv circom /usr/local/bin/
      - run: |
          npm install -g @aiken-lang/aikup snarkjs
          aikup install
          echo "/home/runner/.aiken/bin" >> $GITHUB_PATH
      - name: make init
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          make init
      # NOTE: We are using the minimal circuit, for which way smaller ptau sizes are possible.
      - name: Compile circuit and generate key material
        env:
          W2C2_REV: ${{ steps.w2c2.outputs.rev }}
        run: >
          make prep-tests-bls12-381-minimal
          PTAU_SIZE_BN254=05
          PTAU_SIZE_BLS12381=05
      # Note: This does not run slow tests or tests communicating with a cardano testnet.
      - run: cargo nextest run --locked --no-fail-fast --status-level all -F insecure-circuit -F bls12-381
      - run: cargo test --doc --locked

  cardano-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          npm install -g @aiken-lang/aikup
          aikup install
          echo "/home/runner/.aiken/bin" >> $GITHUB_PATH
      - run: aiken fmt --check
        working-directory: verifier/cardano
      - run: aiken check -D
        working-directory: verifier/cardano
      - run: aiken build
        working-directory: verifier/cardano

